wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1651498465
    t:
      1:
      - 55
      4: 3.8.11
      5: 0.12.15
      8:
      - 1
      - 3
      - 5
